apiVersion: netop.mgr/v1alpha1
kind: ClusterGroupProfile
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"netop.mgr/v1alpha1","kind":"ClusterGroupProfile","metadata":{"annotations":{},"name":"cgp1","namespace":"netop-manager"},"spec":{"selector":{"matchLabels":{"fabric":"k8s-bm-12","site":"Anchorage Site"}}}}
  creationTimestamp: "2023-09-06T09:26:27Z"
  generation: 1
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:selector: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-09-06T09:26:27Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:state: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-09-06T09:26:27Z"
  name: cgp1
  namespace: netop-manager
  resourceVersion: "1351"
  uid: cc962c0b-c991-4d00-9c07-309b226198ed
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        vmm_domain:
          mcast_range: {}
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        sriov_config: {}
      logging: {}
      net_config: {}
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out: {}
      physical_domain: {}
      vrf: {}
    calico_cni_config: {}
    cko_proxy_config: {}
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    context:
      l3out: {}
      vrf: {}
    distro: {}
    fabricinfra: {}
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config: {}
    operator_config: {}
    profile: {}
    registry: {}
    service_mesh_config: {}
    topology: {}
  selector:
    matchLabels:
      fabric: k8s-bm-12
      site: Anchorage Site
status:
  state: true
