apiVersion: netop.mgr/v1alpha1
kind: ClusterNetworkProfile
metadata:
  creationTimestamp: "2023-08-31T09:29:00Z"
  generation: 1
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:aep: {}
              f:vmm_domain:
                .: {}
                f:encap_type: {}
                f:mcast_range:
                  .: {}
                  f:end: {}
                  f:start: {}
                f:nested_inside: {}
            f:kube_config:
              .: {}
              f:drop_log_config: {}
              f:image_pull_policy: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:ovs_memory_limit: {}
              f:sriov_config: {}
            f:logging:
              .: {}
              f:controller_log_level: {}
              f:hostagent_log_level: {}
              f:opflexagent_log_level: {}
            f:net_config:
              .: {}
              f:extern_static: {}
              f:interface_mtu: {}
              f:node_svc_subnet: {}
              f:service_vlan: {}
            f:registry:
              .: {}
              f:acc_provision_operator_version: {}
              f:aci_cni_operator_version: {}
              f:aci_containers_controller_version: {}
              f:aci_containers_host_version: {}
              f:aci_containers_operator_version: {}
              f:cnideploy_version: {}
              f:gbp_version: {}
              f:openvswitch_version: {}
              f:opflex_agent_version: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi:
                .: {}
                f:mtu: {}
              f:vrf: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:physical_domain: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:calico_cni_config: {}
          f:cko_proxy_config:
            .: {}
            f:http_proxy: {}
            f:https_proxy: {}
            f:no_proxy: {}
          f:cni: {}
          f:connectivity_checker:
            .: {}
            f:error_pods_reporting_enable: {}
            f:reachability_test_enable:
              .: {}
              f:external_url:
                .: {}
                f:url: {}
              f:periodic_sync:
                .: {}
                f:enable_updates: {}
                f:interval: {}
            f:reachability_tests: {}
          f:context:
            .: {}
            f:l3out: {}
            f:vrf: {}
          f:distro:
            .: {}
            f:platform: {}
            f:release: {}
            f:type: {}
          f:fabricinfra:
            .: {}
            f:name: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config:
            .: {}
            f:lb_type: {}
          f:monitoring_config:
            .: {}
            f:monitoring_type: {}
            f:remote_write_ip: {}
            f:remote_write_port: {}
          f:net_config:
            .: {}
            f:cluster_svc_subnet: {}
            f:extern_dynamic: {}
            f:kubeapi_vlan: {}
            f:node_subnet: {}
            f:pod_subnet: {}
          f:operator_config:
            .: {}
            f:mode: {}
          f:profile:
            .: {}
            f:ingress: {}
            f:loadbalancer: {}
            f:monitoring: {}
            f:service_mesh: {}
          f:registry:
            .: {}
            f:image_prefix: {}
            f:image_pull_secret: {}
            f:network_operator_version: {}
          f:service_mesh_config:
            .: {}
            f:kubeconfig: {}
            f:mesh_id: {}
            f:name: {}
            f:network: {}
            f:role: {}
          f:topology:
            .: {}
            f:rack: {}
    manager: controller
    operation: Update
    time: "2023-08-31T09:29:00Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:ready: {}
    manager: manager
    operation: Update
    time: "2023-08-31T09:29:00Z"
  name: cnp1
  namespace: netop-manager
  resourceVersion: "16671"
  uid: 790a4064-6d9b-4a9f-a853-34c26ea14fd5
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        aep: bm-srvrs-aep
        vmm_domain:
          encap_type: vxlan
          mcast_range:
            end: 225.114.255.255
            start: 225.114.1.1
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        image_pull_policy: Always
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        ovs_memory_limit: 0.75Gi
        sriov_config: {}
      logging:
        controller_log_level: debug
        hostagent_log_level: debug
        opflexagent_log_level: debug
      net_config:
        extern_static: 10.4.0.1/16
        interface_mtu: 1500
        node_svc_subnet: 10.5.0.1/16
        service_vlan: 102
      registry:
        acc_provision_operator_version: kmr2-test
        aci_cni_operator_version: kmr2-test
        aci_containers_controller_version: kmr2-test
        aci_containers_host_version: kmr2-test
        aci_containers_operator_version: kmr2-test
        cnideploy_version: kmr2-test
        gbp_version: kmr2-test
        openvswitch_version: kmr2-test
        opflex_agent_version: kmr2-test
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi:
          mtu: 1500
        vrf: {}
      l3out:
        external_networks:
        - sauto_l3out-1_epg
        name: sauto_l3out-1
      physical_domain: {}
      vrf:
        name: sauto_l3out-1_vrf
        tenant: common
    calico_cni_config: {}
    cko_proxy_config:
      http_proxy: http://proxy.esl.cisco.com:80
      https_proxy: http://proxy.esl.cisco.com:80
      no_proxy: 10.96.0.1
    cni: aci
    connectivity_checker:
      error_pods_reporting_enable: true
      reachability_test_enable:
        external_url:
          url: google.com
        periodic_sync:
          enable_updates: true
          interval: 60
      reachability_tests:
      - pod_to_pod
      - pod_to_node
      - pod_to_clusterIP
      - pod_to_service
      - pod_to_LB_VIP
      - pod_to_NodePort
      - pod_to_External
      - node_to_node
      - node_to_pod
      - node_to_clusterIP
      - node_to_LB_VIP
    context:
      l3out: {}
      vrf: {}
    distro:
      platform: baremetal
      release: "1.24"
      type: openshift
    fabricinfra:
      name: k8s-bm-2
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config:
      lb_type: Fabric LB
    monitoring_config:
      monitoring_type: prometheus
      remote_write_ip: 3.237.37.136
      remote_write_port: 32307
    net_config:
      cluster_svc_subnet: 10.96.0.0/12
      extern_dynamic: 10.3.0.1/16
      kubeapi_vlan: 101
      node_subnet: 1.100.101.1/24
      pod_subnet: 10.6.0.1/16
    operator_config:
      mode: managed
    profile:
      ingress: Ngnix
      loadbalancer: Fabric LB
      monitoring: prometheus
      service_mesh: bm2acicni
    registry:
      image_prefix: quay.io/noirolabs
      image_pull_secret: noiro-docker-registry-secret
      network_operator_version: cko-mvp-1
    service_mesh_config:
      kubeconfig: https://github.com/networkoperator/demo-clusters/tree/kiran/aci-cni-cluster
      mesh_id: mesh1
      name: bm2acicni
      network: network1
      role: Primary
    topology:
      rack:
      - {}
status:
  ready: true
