apiVersion: netop.mgr/v1alpha1
kind: FabricInfra
metadata:
  creationTimestamp: "2023-08-31T10:08:46Z"
  finalizers:
  - fabricinfra.netop.mgr/finalizer
  generation: 1
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:bgp:
          .: {}
          f:aci_as_number: {}
          f:remote_as_numbers: {}
        f:contexts:
          .: {}
          f:1:
            .: {}
            f:aep: {}
            f:l3out: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:2:
            .: {}
            f:aep: {}
            f:l3out: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
        f:credentials:
          .: {}
          f:hosts: {}
          f:secretRef:
            .: {}
            f:name: {}
        f:external_subnets: {}
        f:fabric_type: {}
        f:infra_vlan: {}
        f:internal_subnets: {}
        f:leafs: {}
        f:mcast_subnets: {}
        f:pod_subnets: {}
        f:provision_fabric: {}
        f:spines: {}
        f:topology:
          .: {}
          f:rack: {}
        f:vlans: {}
    manager: controller
    operation: Update
    time: "2023-08-31T10:08:46Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"fabricinfra.netop.mgr/finalizer": {}
      f:status:
        .: {}
        f:available:
          .: {}
          f:contexts:
            .: {}
            f:1:
              .: {}
              f:aep: {}
              f:l3out: {}
              f:vrf:
                .: {}
                f:name: {}
                f:tenant: {}
            f:2:
              .: {}
              f:aep: {}
              f:l3out: {}
              f:vrf:
                .: {}
                f:name: {}
                f:tenant: {}
          f:external_subnets: {}
          f:internal_subnets: {}
          f:mcast_subnets: {}
          f:pod_subnets: {}
          f:remote_as_numbers: {}
          f:vlans: {}
        f:ready: {}
    manager: manager
    operation: Update
    time: "2023-08-31T10:08:46Z"
  name: k8s-bm-83
  namespace: netop-manager
  resourceVersion: "22360"
  uid: 4748cb84-240c-4d45-bbf5-a7c3f085abab
spec:
  bgp:
    aci_as_number: 2
    remote_as_numbers:
    - 64512
  contexts:
    "1":
      aep: bm-srvrs-aep
      l3out: {}
      vrf:
        name: sauto_l3out-1_vrf
        tenant: common
    "2":
      aep: bm-srvrs-calico-aep
      l3out: {}
      vrf:
        name: sauto_l3out-3_vrf
        tenant: common
  credentials:
    hosts:
    - 10.30.120.140
    secretRef:
      name: apic-credentials
  external_subnets:
  - 10.3.0.1/16
  fabric_type: aci
  infra_vlan: 4093
  internal_subnets:
  - 1.100.101.1/16
  leafs: 7
  mcast_subnets:
  - 225.114.0.0/16
  pod_subnets:
  - 10.7.0.1/16
  provision_fabric: false
  spines: 7
  topology:
    rack:
    - aci_pod_id: 1
      id: 1
      leaf:
      - id: 101
      - id: 102
      node:
      - name: k8s-node1
      - name: k8s-node2
    - aci_pod_id: 1
      id: 2
      leaf:
      - id: 103
      - id: 104
      node:
      - name: k8s-node3
      - name: k8s-node4
  vlans:
  - 101
  - 102
  - 103
  - 104
status:
  available:
    contexts:
      "1":
        aep: bm-srvrs-aep
        l3out: {}
        vrf:
          name: sauto_l3out-1_vrf
          tenant: common
      "2":
        aep: bm-srvrs-calico-aep
        l3out: {}
        vrf:
          name: sauto_l3out-3_vrf
          tenant: common
    external_subnets:
    - 10.3.0.1/16
    internal_subnets:
    - 1.100.101.1/16
    mcast_subnets:
    - 225.114.0.0/16
    pod_subnets:
    - 10.7.0.1/16
    remote_as_numbers:
    - 64512
    vlans:
    - 101
    - 102
    - 103
    - 104
  ready: true
